Repository cognitedata/pygen, pull requests merged in 2025-05, with the labels that each got.

#462 [PYG-375] 🚅 UV package manager
  .github/workflows/build.yml
  .github/workflows/release.yaml
  .pre-commit-config.yaml
  examples/cognite_core/_api_client.py
  examples/omni/_api_client.py
  examples/omni_multi/_api_client.py
  examples/omni_sub/_api_client.py
  examples/wind_turbine/_api_client.py
  poetry.lock
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing, waiting-for-risk-review

#469 [PYG-376] 👹 Include version in wheel
  cognite/pygen/_build.py
  tests/test_unit_slow/test_generator/test_build.py
Labels: risk-review-ongoing, waiting-for-team

#474 [PYG-385] 😦 Unexpected retrieve behavior
  cognite/pygen/_core/models/data_classes.py
  examples/cognite_core/data_classes/_cognite_360_image_annotation.py
  examples/cognite_core/data_classes/_cognite_360_image_collection.py
  examples/cognite_core/data_classes/_cognite_cad_revision.py
  examples/cognite_core/data_classes/_cognite_point_cloud_revision.py
  tests/test_unit/test_api/test_generate_sdk.py
Labels: waiting-for-risk-review

#475 ci: fix twine upload
  .github/workflows/release.yaml
Labels: waiting-for-risk-review

#478 Restrict python version to less than 4
  pyproject.toml
  uv.lock
Labels: risk-review-ongoing, waiting-for-team
